import type { NationStats } from "./index";

export type CanonNation = NationStats & {
  spin: string;
};

export const canonNations: CanonNation[] = [
  {
    spin: "#1",
    name: "Primis",
    slug: "primis",
    people: "25M",
    government: "Colony - Military Government",
    gdp: "500k",
    economy: "Tech & Oil",
    military: "Large 5 / 11",
    geoPoliticalStatus: "Colony of Moravia",
    block: "Defence Accords",
  },
  {
    spin: "#2",
    name: "Melandia",
    slug: "melandia",
    people: "750M",
    government: "Monarchy",
    gdp: "6M",
    economy: "Geothermal / Gems",
    military: "Air Superpower 7 / 11",
    geoPoliticalStatus: "War (vs Lithuania)",
    block: "None",
  },
  {
    spin: "#3",
    name: "Isma",
    slug: "isma",
    people: "1M",
    government: "Fallen Empire",
    gdp: "500k",
    economy: "Finance / Gems",
    military: "None 0 / 11",
    geoPoliticalStatus: "War (vs Vladaria)",
    block: "None",
  },
  {
    spin: "#4",
    name: "Yoggy",
    slug: "yoggy",
    people: "60M",
    government: "Junta",
    gdp: "900k",
    economy: "Textiles / Minerals",
    military: "Naval Superpower 7 / 11",
    geoPoliticalStatus: "Hostile (vs Zandoro)",
    block: "None",
  },
  {
    spin: "#5",
    name: "Liberterra (Ourterra)",
    slug: "liberterra",
    people: "150M",
    government: "Communist Democracy",
    gdp: "100k",
    economy: "Freshwater",
    military: "Small Defensive 2 / 11",
    geoPoliticalStatus: "Freeze (vs Imeria)",
    block: "Novus Ordo Mundi",
  },
  {
    spin: "#6",
    name: "Belvion",
    slug: "belvion",
    people: "80M",
    government: "Republic",
    gdp: "600k",
    economy: "Energy / Textiles",
    military: "Continental Power 9 / 11",
    geoPoliticalStatus: "War (vs Freelandia)",
    block: "None",
  },
  {
    spin: "#7",
    name: "Fredya",
    slug: "fredya",
    people: "400M",
    government: "Technocracy",
    gdp: "400k",
    economy: "$2.5T Manuf. / Fire god",
    military: "Medium 4 / 11",
    geoPoliticalStatus: "Techno-Magic",
    block: "None",
  },
  {
    spin: "#8",
    name: "Nordmere",
    slug: "nordmere",
    people: "30M",
    government: "Constitutional Monarchy",
    gdp: "400k",
    economy: "$150B Green Economy",
    military: "Small 2 / 11",
    geoPoliticalStatus: "Rival (Shadow Conf.)",
    block: "Novus Ordo Mundi",
  },
  {
    spin: "#9",
    name: "Catomane",
    slug: "catomane",
    people: "50M",
    government: "Stratocracy",
    gdp: "400k",
    economy: "$5T Innovation / Fire god",
    military: "Special Forces 7 / 11",
    geoPoliticalStatus: "Tension (vs Omaleko)",
    block: "Novus Ordo Mundi",
  },
  {
    spin: "#10",
    name: "Dalgaristan",
    slug: "dalgaristan",
    people: "175M",
    government: "Socialist Republic",
    gdp: "900k",
    economy: "$2T Surveillance",
    military: "Advanced 6 / 11",
    geoPoliticalStatus: "Former War (vs URHNB)",
    block: "POF Alliance",
  },
  {
    spin: "#11",
    name: "Northern Lights",
    slug: "northern-lights",
    people: "40M",
    government: "Ritualistic Kingdom",
    gdp: "800k",
    economy: "$100B Pharma",
    military: "Continental Power 9 / 11",
    geoPoliticalStatus: "Dual Rituals",
    block: "None",
  },
  {
    spin: "#12",
    name: "Moradior",
    slug: "moradior",
    people: "175M",
    government: "Robotic Dominion",
    gdp: "750k",
    economy: "$2.5T Robotics",
    military: "Regional Power 8 / 11",
    geoPoliticalStatus: "War (vs Rei-Kai)",
    block: "Defence Accords",
  },
  {
    spin: "#13",
    name: "Great Lithuania (DIVIDED)",
    slug: "great-lithuania",
    people: "60M",
    government: "Expansionist Republic",
    gdp: "1M",
    economy: "$50B Healthcare",
    military: "Expansionist 10 / 11",
    geoPoliticalStatus: "War (vs Melandia [Lost])",
    block: "None",
  },
  {
    spin: "#14",
    name: "Maronia",
    slug: "maronia",
    people: "100M",
    government: "Traditional Kingdom",
    gdp: "9M",
    economy: "$700B Agriculture / Mythology",
    military: "Air Superpower 7 / 11",
    geoPoliticalStatus: "Freeze (vs Belvion)",
    block: "None",
  },
  {
    spin: "#15",
    name: "Daroille",
    slug: "daroille",
    people: "15M",
    government: "Corporate Confederation",
    gdp: "100k",
    economy: "$3T Casinos",
    military: "Medium 4 / 11",
    geoPoliticalStatus: "Allied (Qashira)",
    block: "Novus Ordo Mundi",
  },
  {
    spin: "#16",
    name: "Torenza",
    slug: "torenza",
    people: "50M",
    government: "Authoritarian Republic",
    gdp: "600k",
    economy: "$6T Space / Human",
    military: "Expansionist 10 / 11",
    geoPoliticalStatus: "Allied (Primis)",
    block: "Defence Accords",
  },
  {
    spin: "#17",
    name: "Imeria",
    slug: "imeria",
    people: "5M",
    government: "Colony - Feudal Warlords",
    gdp: "10k",
    economy: "$400B Warlords",
    military: "Standard 3 / 11",
    geoPoliticalStatus: "Colony of Vienzerna",
    block: "None",
  },
  {
    spin: "#18",
    name: "Wonderia",
    slug: "wonderia",
    people: "80M",
    government: "Colony - Cybernetic Regency",
    gdp: "750k",
    economy: "$400B Cybernetics",
    military: "Cyber Hegemony / Cyberwarfare 11 / 11",
    geoPoliticalStatus: "Prot. of Yoggy",
    block: "None",
  },
  {
    spin: "#19",
    name: "B. Obrero",
    slug: "b-obrero",
    people: "750k",
    government: "Progressive Union",
    gdp: "50k",
    economy: "$500M Church Tax",
    military: "Standard 3 / 11",
    geoPoliticalStatus: "PARIAH",
    block: "HATED BY ALL",
  },
  {
    spin: "#20",
    name: "Vienzerna",
    slug: "vienzerna",
    people: "125M",
    government: "Trade Empire",
    gdp: "750k",
    economy: "$3.5T Guilds",
    military: "Expansionist 10 / 11",
    geoPoliticalStatus: "Colonizer",
    block: "None",
  },
  {
    spin: "#21",
    name: "Vladaria",
    slug: "vladaria",
    people: "5M",
    government: "Theocratic Kingdom",
    gdp: "200k",
    economy: "$1B AI / Ditopism",
    military: "Standard 3 / 11",
    geoPoliticalStatus: "War (vs Isma)",
    block: "Royal Wedding alliance",
  },
  {
    spin: "#22",
    name: "Bernaland",
    slug: "bernaland",
    people: "5M",
    government: "Federal Republic",
    gdp: "200k",
    economy: "$1B Robotics",
    military: "Standard 3 / 11",
    geoPoliticalStatus: "Allied (Scopeople)",
    block: "Novus Ordo Mundi",
  },
  {
    spin: "#23",
    name: "Plesshurye",
    slug: "plesshurye",
    people: "500M",
    government: "Democratic Republic",
    gdp: "800k",
    economy: "$6T Finance / Space",
    military: "Spatial Superpower 7 / 11",
    geoPoliticalStatus: "Exploration Culture",
    block: "None",
  },
  {
    spin: "#24",
    name: "Rei-Kai",
    slug: "rei-kai",
    people: "70M",
    government: "Fascist Empire",
    gdp: "500k",
    economy: "$7T Biotech",
    military: "Advanced 6 / 11",
    geoPoliticalStatus: "War (vs Moradior)",
    block: "POF Alliance",
  },
  {
    spin: "#25",
    name: "Zharak-Ten",
    slug: "zharak-ten",
    people: "200M",
    government: "Maritime Democracy",
    gdp: "900k",
    economy: "$500B Fish / Ent. / Shamanic",
    military: "Advanced 6 / 11",
    geoPoliticalStatus: "Allied (Navatonia)",
    block: "Novus Ordo Mundi",
  },
  {
    spin: "#26",
    name: "Zottegem",
    slug: "zottegem",
    people: "30M",
    government: "Financial Oligarchy",
    gdp: "400k",
    economy: "$40B Shadow Bank",
    military: "Small Defensive 2 / 11",
    geoPoliticalStatus: "Allied (Moradior)",
    block: "Defence Accords",
  },
  {
    spin: "#27",
    name: "Fish State",
    slug: "fish-state",
    people: "25M",
    government: "Naval Junta",
    gdp: "300k",
    economy: "$400B Maritime",
    military: "Large 5 / 11",
    geoPoliticalStatus: "War (vs Imeria)",
    block: "None",
  },
  {
    spin: "#28",
    name: "Anuruthor",
    slug: "anuruthor",
    people: "40M",
    government: "Protectorate",
    gdp: "500k",
    economy: "$1T Heavy Industry",
    military: "Small Defensive 2 / 11",
    geoPoliticalStatus: "Rival (vs Rei-Kai)",
    block: "None",
  },
  {
    spin: "#29",
    name: "Shadow Conf.",
    slug: "shadow-conf",
    people: "175M",
    government: "Pirate Confederation",
    gdp: "500k",
    economy: "$1.5T Piracy",
    military: "Large 5 / 11",
    geoPoliticalStatus: "Rival (vs Nordmere)",
    block: "None",
  },
  {
    spin: "#30",
    name: "Tunguska",
    slug: "tunguska",
    people: "750k",
    government: "Colony - Clan Council",
    gdp: "175k",
    economy: "$200B Ritual Tour.",
    military: "Small Defensive 2 / 11",
    geoPoliticalStatus: "Colony of U. Tribes",
    block: "Novus Ordo Mundi",
  },
  {
    spin: "#31",
    name: "C. Ranchers",
    slug: "c-ranchers",
    people: "10M",
    government: "Anarchist Commune",
    gdp: "100k",
    economy: "$5B Ranching",
    military: "Regional Influence Army 8 / 11",
    geoPoliticalStatus: "Anarchist",
    block: "Royal Wedding alliance",
  },
  {
    spin: "#32",
    name: "Solaria",
    slug: "solaria",
    people: "100M",
    government: "Federal Empire",
    gdp: "60k",
    economy: "$9T Shadow Banking",
    military: "Large 5 / 11",
    geoPoliticalStatus: "Defense Pact (Dalgaristan)",
    block: "POF Alliance",
  },
  {
    spin: "#33",
    name: "Skressia",
    slug: "skressia",
    people: "15M",
    government: "Drone Republic",
    gdp: "1k",
    economy: "$50B Drones",
    military: "Standard 3 / 11",
    geoPoliticalStatus: "War (vs Azur Axis)",
    block: "None",
  },
  {
    spin: "#34",
    name: "Great Moravia",
    slug: "great-moravia",
    people: "900M",
    government: "Cyber Dictatorship",
    gdp: "3M",
    economy: "$8T Cyber / Loans",
    military: "WORLD MENACE 11 /11",
    geoPoliticalStatus: "War (vs Golden Land)",
    block: "Defence Accords",
  },
  {
    spin: "#35",
    name: "ABOC",
    slug: "aboc",
    people: "700M",
    government: "Decentralized Union",
    gdp: "90k",
    economy: "$1T Waste Mgt",
    military: "None 0 / 11",
    geoPoliticalStatus: "Trade (Rei-Kai)",
    block: "None",
  },
  {
    spin: "#36",
    name: "Voidia",
    slug: "voidia",
    people: "40M",
    government: "Agrarian Monarchy",
    gdp: "200k",
    economy: "$500B Agriculture - Alien Cult",
    military: "Continental Power 9 / 11",
    geoPoliticalStatus: "Freeze (vs Maronia)",
    block: "None",
  },
  {
    spin: "#37",
    name: "Runonno",
    slug: "runonno",
    people: "25M",
    government: "Military Superstate",
    gdp: "800k",
    economy: "$1T Security",
    military: "Land Superpower 7 / 11",
    geoPoliticalStatus: "VS EVERYONE",
    block: "None",
  },
  {
    spin: "#38",
    name: "Azur Axis",
    slug: "azur-axis",
    people: "40M",
    government: "AI Corporatocracy",
    gdp: "500k",
    economy: "$900B Shell / AI",
    military: "Small Defensive 2 / 11",
    geoPoliticalStatus: "War (vs Skressia)",
    block: "None",
  },
  {
    spin: "#39",
    name: "Freelandia",
    slug: "freelandia",
    people: "15M",
    government: "Industrial Republic",
    gdp: "350k",
    economy: "$900B Heavy Ind.",
    military: "Regional Power 8 / 11",
    geoPoliticalStatus: "War (vs Belvion)",
    block: "None",
  },
  {
    spin: "#40",
    name: "40 Aragon",
    slug: "40-aragon",
    people: "80M",
    government: "Media Monarchy",
    gdp: "350k",
    economy: "$3T Entertainment",
    military: "Continental Power 9 / 11",
    geoPoliticalStatus: "Allied (Whiterun)",
    block: "Novus Ordo Mundi",
  },
  {
    spin: "#41",
    name: "Scopeople",
    slug: "scopeople",
    people: "30M",
    government: "Tribal Kingdom",
    gdp: "175k",
    economy: "$1B Local Trade",
    military: "None 0 / 11",
    geoPoliticalStatus: "Allied (Bernaland)",
    block: "Novus Ordo Mundi",
  },
  {
    spin: "#42",
    name: "Aura Sancta",
    slug: "aura-sancta",
    people: "500M",
    government: "Empire",
    gdp: "12M",
    economy: "$10T Tourism",
    military: "WORLD POLICE 11 / 11",
    geoPoliticalStatus: "World Peace Doctrine",
    block: "Novus Ordo Mundi",
  },
  {
    spin: "#43",
    name: "Navatonia",
    slug: "navatonia",
    people: "300M",
    government: "Shamanic Republic",
    gdp: "750k",
    economy: "$3T Mining / Shaman",
    military: "Regional Power 8 / 11",
    geoPoliticalStatus: "Allied (Zharak-Ten)",
    block: "Novus Ordo Mundi",
  },
  {
    spin: "#44",
    name: "Abolitionist G.",
    slug: "abolitionist-g",
    people: "200M",
    government: "Guild Republic",
    gdp: "75k",
    economy: "$9T Black Market",
    military: "Continental Power 9 / 11",
    geoPoliticalStatus: "PARIAH",
    block: "HATED BY ALL",
  },
  {
    spin: "#45",
    name: "Golden Land",
    slug: "golden-land",
    people: "25M",
    government: "Mercantile Democracy",
    gdp: "125k",
    economy: "$3T Grey Market",
    military: "Continental Power 9 / 11",
    geoPoliticalStatus: "War (vs Moravia)",
    block: "None",
  },
  {
    spin: "#46",
    name: "Whiterun",
    slug: "whiterun",
    people: "30M",
    government: "Academic Republic",
    gdp: "300k",
    economy: "$600B Education",
    military: "Medium Army 4 / 11",
    geoPoliticalStatus: "Allied (Aragon)",
    block: "Novus Ordo Mundi",
  },
  {
    spin: "#47",
    name: "United Tribes",
    slug: "united-tribes",
    people: "10M",
    government: "Tribal Confederation",
    gdp: "200k",
    economy: "$400B Green Econ",
    military: "Medium Army 4 / 11",
    geoPoliticalStatus: "Parent of Tunguska",
    block: "Novus Ordo Mundi",
  },
  {
    spin: "#48",
    name: "Icelania",
    slug: "icelania",
    people: "125M",
    government: "Pharma Republic",
    gdp: "400k",
    economy: "$14T Pharma / Manuf",
    military: "Advanced Army 6 / 11",
    geoPoliticalStatus: "Rival (Catomane)",
    block: "None",
  },
  {
    spin: "#49",
    name: "Omaleko",
    slug: "omaleko",
    people: "400M",
    government: "Social Commonwealth",
    gdp: "1M",
    economy: "$12T Oil / Auto",
    military: "Standard 3 / 11",
    geoPoliticalStatus: "Tension (Catomane)",
    block: "Defence Accords",
  },
  {
    spin: "#50",
    name: "Rootbeerism",
    slug: "rootbeerism",
    people: "80M",
    government: "Corporate State",
    gdp: "200k",
    economy: "$1T Call Centers",
    military: "Special Forces 7 / 11",
    geoPoliticalStatus: "Trade (Runonno)",
    block: "None",
  },
  {
    spin: "#51",
    name: "Dowenia",
    slug: "dowenia",
    people: "1.2B",
    government: "Crypto Anarchy",
    gdp: "1M",
    economy: "$5T Crypto / Bank",
    military: "None 0 / 11",
    geoPoliticalStatus: "Underground Networks",
    block: "None",
  },
  {
    spin: "#52",
    name: "Schizolandia",
    slug: "schizolandia",
    people: "100k",
    government: "People's Union",
    gdp: "40k",
    economy: "$50M Cultural / Druidic",
    military: "Small Defensive 2 / 11",
    geoPoliticalStatus: "Hostile (Moravia)",
    block: "Novus Ordo Mundi",
  },
  {
    spin: "#53",
    name: "Lumenie",
    slug: "lumenie",
    people: "5M",
    government: "Colony - Nomadics",
    gdp: "125k",
    economy: "$100M AI / Robots",
    military: "Standard 3 / 11",
    geoPoliticalStatus: "Prot. of B. Obrero",
    block: "Novus Ordo Mundi",
  },
  {
    spin: "#54",
    name: "URHNB",
    slug: "urhnb",
    people: "15M",
    government: "United Republics",
    gdp: "900k",
    economy: "$100B Defense",
    military: "Continental Power 9 / 11",
    geoPoliticalStatus: "Former War (vs Dalgaristan)",
    block: "None",
  },
  {
    spin: "#55",
    name: "Black Cult",
    slug: "black-cult",
    people: "250M",
    government: "Expansionist Theocracy",
    gdp: "500k",
    economy: "$7T Energy / Manuf",
    military: "Expansionist 10 / 11",
    geoPoliticalStatus: "PARIAH",
    block: "HATED BY ALL",
  },
  {
    spin: "#56",
    name: "Greater Celtia",
    slug: "greater-celtia",
    people: "90M",
    government: "Clan Empire",
    gdp: "$30T",
    economy: "Cloning",
    military: "Air Superpower 7 / 11",
    geoPoliticalStatus: "Rival (Solaria)",
    block: "None",
  },
  {
    spin: "#57",
    name: "Sabrayana",
    slug: "sabrayana",
    people: "2.5B",
    government: "Magical Empire",
    gdp: "$12T",
    economy: "Magic Cards - Shamanic",
    military: "Expansionist Power",
    area: "12 300 000 km2",
    geoPoliticalStatus: "Allied (Melandia)",
    block: "None",
  },
  {
    spin: "#58",
    name: "Aesyl",
    slug: "aesyl",
    people: "7M",
    government: "Independent Commune",
    gdp: "40k",
    economy: "$150B Wooden Chairs",
    military: "Advanced Army 6 / 11",
    geoPoliticalStatus: "Guaranteed by ALL",
    block: "Global Arbiter (HQ)",
  },
  {
    spin: "#59",
    name: "Techlandia",
    slug: "techlandia",
    people: "60M",
    government: "Technocracy",
    gdp: "500k",
    economy: "$8T Space / Nuclear",
    military: "Spatial Superpower 7 / 11",
    geoPoliticalStatus: "Allied (Navatonia)",
    block: "Novus Ordo Mundi",
  },
  {
    spin: "#60",
    name: "Black League",
    slug: "black-league",
    people: "150M",
    government: "Forced Labor Union",
    gdp: "800k",
    economy: "$5T Forced Labor",
    military: "Land Superpower 7 / 11",
    geoPoliticalStatus: "War (vs Belvion)",
    block: "None",
  },
  {
    spin: "#61",
    name: "Norasia",
    slug: "norasia",
    people: "250k",
    government: "Republic",
    gdp: "75k",
    economy: "$20B Salt Monopoly",
    military: "Small Defensive 2 / 11",
    geoPoliticalStatus: "Allied (Dalgaristan)",
    block: "None",
  },
  {
    spin: "#62",
    name: "Rootberia",
    slug: "rootberia",
    people: "3M",
    government: "Gambling State",
    gdp: "40k",
    economy: "$30B Gambling",
    military: "Small Defensive 2 / 11",
    geoPoliticalStatus: "Trade (Voidia)",
    block: "None",
  },
  {
    spin: "#63",
    name: "Solandria",
    slug: "solandria",
    people: "15M",
    government: "Colony",
    gdp: "250k",
    economy: "$700B Cybernetics / Fire god",
    military: "Standard 3 / 11",
    geoPoliticalStatus: "Colony of Sabrayana",
    block: "None",
  },
  {
    spin: "#64",
    name: "Traguera",
    slug: "traguera",
    people: "5M",
    government: "Authoritarian Republic",
    gdp: "Not Specified",
    economy: "$15B Addiction Food",
    military: "Standard 3 / 11",
    geoPoliticalStatus: "Allied (Golden Land)",
    block: "None",
  },
  {
    spin: "#65",
    name: "Dravencia",
    slug: "dravencia",
    people: "150M",
    government: "Fascist State",
    gdp: "400k",
    economy: "$12T Rare Wood",
    military: "Large Army 5 / 11",
    geoPoliticalStatus: "Allied (Anuruthor)",
    block: "None",
  },
  {
    spin: "#66",
    name: "Zhiva-Zarina",
    slug: "zhiva-zarina",
    people: "5M",
    government: "Confederation",
    gdp: "450k",
    economy: "$90B Health / Auto",
    military: "Small Defensive 2 / 11",
    geoPoliticalStatus: "Trade (Belvion)",
    block: "None",
  },
  {
    spin: "#67",
    name: "Qashira",
    slug: "qashira",
    people: "10M",
    government: "Parliamentary Democracy",
    gdp: "400k",
    economy: "$900B Education",
    military: "Regional Power 8 / 11",
    geoPoliticalStatus: "Allied (Daroille)",
    block: "Novus Ordo Mundi",
  },
  {
    spin: "#68",
    name: "Karakum",
    slug: "karakum",
    people: "3M",
    government: "Communist Republic",
    gdp: "300k",
    economy: "$4B Hydropower",
    military: "None 0 / 11",
    geoPoliticalStatus: "Prot. (B. Obrero)",
    block: "Novus Ordo Mundi",
  },
  {
    spin: "#69",
    name: "Zandoro",
    slug: "zandoro",
    people: "4M",
    government: "Military Dictatorship",
    gdp: "175k",
    economy: "$110B Art / Bananas",
    military: "Large Army 5 / 11",
    geoPoliticalStatus: "Hostile (Yoggy)",
    block: "None",
  },
  {
    spin: "#70",
    name: "Zubrossya",
    slug: "zubrossya",
    people: "15M",
    government: "Communist Republic",
    gdp: "450k",
    economy: "$500B Global Data",
    military: "Advanced Army 6 / 11",
    geoPoliticalStatus: "Tension (Moravia)",
    block: "None",
  },
  {
    spin: "#71",
    name: "Yerna",
    slug: "yerna",
    people: "250M",
    government: "Fascist Republic",
    gdp: "1M",
    economy: "$9T Lit. / Subscriptions",
    military: "Land Superpower 7 / 11",
    geoPoliticalStatus: "Influence (Moradior)",
    block: "Defence Accords",
  },
  {
    spin: "#72",
    name: "Katzash",
    slug: "katzash",
    people: "50M",
    government: "Federal Democracy",
    gdp: "800k",
    economy: "$1T Paper / Innov.",
    military: "Expansionist 10 / 11",
    geoPoliticalStatus: "Allied (Moravia)",
    block: "Defence Accords",
  },
  {
    spin: "#73",
    name: "Syrenthia",
    slug: "syrenthia",
    people: "250k",
    government: "Colony - Warrior Council",
    gdp: "60k",
    economy: "$40B Mercenaries",
    military: "Special Forces 7 / 11",
    geoPoliticalStatus: "Prot. of Moravia",
    block: "Defence Accords",
  },
  {
    spin: "#74",
    name: "Xentael",
    slug: "xentael",
    people: "7M",
    government: "Communist State",
    gdp: "150k",
    economy: "$150B Nuc. Waste",
    military: "Medium Army 4 / 11",
    geoPoliticalStatus: "Trade (Rei-Kai)",
    block: "None",
  },
  {
    spin: "#75",
    name: "Ditopia",
    slug: "ditopia",
    people: "1M",
    government: "Theocracy",
    gdp: "20k",
    economy: "$90B Rails / Holy / Ditopism",
    military: "Advanced Army 6 / 11",
    geoPoliticalStatus: "Non-Aligned",
    block: "Global Arbiter",
  },
  {
    spin: "#76",
    name: "Veltaris",
    slug: "veltaris",
    people: "125M",
    government: "Absolute Monarchy",
    gdp: "1M",
    economy: "$18T Monopolies",
    military: "WORLD ARBITER 11 / 11",
    geoPoliticalStatus: "Non-Aligned",
    block: "Global Arbiter",
  },
  {
    spin: "#77",
    name: "Santa Kova",
    slug: "santa-kova",
    people: "115M",
    government: "Confederation",
    gdp: "1M",
    economy: "$2T Literrature and Voice acting",
    military: "Naval Superpower 7 / 11",
    geoPoliticalStatus: "South Defence Accords",
    block: "Defence Accords",
  },
  {
    spin: "#78",
    name: "ShieldHolm",
    slug: "shieldholm",
    people: "10M",
    government: "Authoritarian Republic",
    gdp: "750k",
    economy: "$500B Troll farm - Cloning",
    military: "Medium Army 4 / 11",
    geoPoliticalStatus: "Non-Aligned",
    block: "None",
  },
  {
    spin: "#79",
    name: "Kingdom of Maple",
    slug: "kingdom-of-maple",
    people: "30M",
    government: "Monarchy",
    gdp: "900k",
    economy: "$900B Oil / Gas and Anime",
    military: "Army Alliances 7 / 11",
    geoPoliticalStatus: "POF Alliance",
    block: "POF Alliance",
  },
  {
    spin: "#80",
    name: "Britonia",
    slug: "britonia",
    people: "5M",
    government: "Military Dictatorship",
    gdp: "3M",
    economy: "$90B Corruption",
    military: "Standard 3 / 11",
    geoPoliticalStatus: "Not Specified",
    block: "Defence Accords",
  },
  {
    spin: "#81",
    name: "Chungun Republic",
    slug: "chungun-republic",
    people: "50M",
    government: "Presidential Republic",
    gdp: "500k",
    economy: "$900B Healthcare",
    military: "Medium Army 4 / 11",
    geoPoliticalStatus: "Not Specified",
    block: "Defence Accords",
  },
  {
    spin: "#82",
    name: "Cordolia",
    slug: "cordolia",
    people: "30M",
    government: "Communist State",
    gdp: "3M",
    economy: "$1T Cybernetics and Shadow trade",
    military: "Cybernetics Army 7 / 11",
    geoPoliticalStatus: "Non-Aligned",
    block: "None",
  },
  {
    spin: "#83",
    name: "Golden River Confederation",
    slug: "golden-river-confederation",
    people: "7M",
    government: "Confederation",
    gdp: "450k",
    economy: "$8T Bananas and Maritime trade",
    military: "Naval Superpower 7 / 11",
    geoPoliticalStatus: "POF Alliance",
    block: "POF Alliance",
  },
  {
    spin: "#84",
    name: "Great Valoria",
    slug: "great-valoria",
    people: "25M",
    government: "Shamanic Council",
    gdp: "600k",
    economy: "$500B Church tax",
    military: "Medium Army 4 / 11",
    geoPoliticalStatus: "Non-Aligned",
    block: "None",
  },
  {
    spin: "#85",
    name: "Royal Guild of Jamland",
    slug: "royal-guild-of-jamland",
    people: "7M",
    government: "Guild Merchant State",
    gdp: "$300B",
    economy: "Manufacturing",
    military: "Small defensive army 4 / 11",
    area: "300 000 km2",
    geoPoliticalStatus: "Non-Aligned",
    block: "None",
    hdi: "0.84",
  },
  {
    spin: "#86",
    name: "United Geats",
    slug: "united-geats",
    people: "200M",
    government: "Parliamentary Democracy",
    gdp: "$10T",
    economy: "Agriculture & Textile",
    military: "Large army",
    area: "6 000 000 km2",
    geoPoliticalStatus: "Non-Aligned",
    block: "None",
    culture: "Isolation. & Oral trad.",
    hdi: "0.82",
  },
  {
    spin: "#87",
    name: "Geometrizan",
    slug: "geometrizan",
    people: "2M",
    government: "Parliamentary Democracy",
    gdp: "$100B",
    economy: "Tourist exploitation",
    military: "Standard army",
    area: "60 000 km2",
    geoPoliticalStatus: "Non-Aligned",
    block: "POF (Member)",
    culture: "Urban & Progressive",
    hdi: "0.88",
  },
  {
    spin: "#88",
    name: "Union of Man and Nature",
    slug: "union-of-man-and-nature",
    people: "7M",
    government: "Colony - Plesshurye",
    gdp: "$300B",
    economy: "Hydropower",
    military: "Medium army",
    area: "900 000 km2",
    geoPoliticalStatus: "Non-Aligned",
    block: "None",
    culture: "Mystical Nature",
    hdi: "0.71",
  },
  {
    spin: "#89",
    name: "New Eldia",
    slug: "new-eldia",
    people: "40M",
    government: "Authoritarian Republic",
    gdp: "$4T",
    economy: "Social Credit & Voice acting",
    military: "Regional military",
    area: "450 000 km2",
    geoPoliticalStatus: "Non-Aligned",
    block: "None",
    culture: "Name changing / Magic",
    hdi: "0.79",
  },
  {
    spin: "#90",
    name: "Republic of the Sun",
    slug: "republic-of-the-sun",
    people: "30M",
    government: "Theocracy (Fire God)",
    gdp: "$10T",
    economy: "Tax Haven & Shadow bank",
    military: "Advanced military",
    area: "300 000 km2",
    geoPoliticalStatus: "Non-Aligned",
    block: "None",
    culture: "Festival / Dance",
    hdi: "0.94",
  },
  {
    spin: "#91",
    name: "Autrian Empire",
    slug: "autrian-empire",
    people: "90M",
    government: "Empire",
    gdp: "$14T",
    economy: "Private Security & Heavy Industry",
    military: "Expansionist Army",
    area: "1 000 000 km2",
    geoPoliticalStatus: "Non-Aligned",
    block: "None",
    culture: "Ancestor / minimalist",
    hdi: "0.91",
  },
  {
    spin: "#92",
    name: "Bobak Republic",
    slug: "bobak-republic",
    people: "6M",
    government: "Republic",
    gdp: "$25T",
    economy: "Crypto (Bobakoins)",
    military: "Standard Army",
    area: "250 000 km2",
    geoPoliticalStatus: "Non-Aligned",
    block: "None",
    culture: "Corporate",
    hdi: "0.59",
  },
  {
    spin: "#93",
    name: "Xonisia",
    slug: "xonisia",
    people: "40M",
    government: "Constitutional Monarchy",
    gdp: "$3T",
    economy: "Sub Sea Cable",
    military: "Large Army",
    area: "350 000 km2",
    geoPoliticalStatus: "Non-Aligned",
    block: "POF (Member)",
    culture: "Scientific",
    hdi: "0.99",
  },
  {
    spin: "#94",
    name: "Socialist Federation Of Calradia",
    slug: "socialist-federation-of-calradia",
    people: "550k",
    government: "Communist State",
    gdp: "$40B",
    economy: "Corruption",
    military: "Standard Army",
    area: "500 000 km2",
    geoPoliticalStatus: "Non-Aligned",
    block: "None",
    culture: "Fraternity",
    hdi: "0.60",
  },
  {
    spin: "#95",
    name: "Altergrad",
    slug: "altergrad",
    people: "30M",
    government: "Federal Republic",
    gdp: "$700B",
    economy: "Publishing & Pure water",
    military: "Large Army",
    area: "200 000 km2",
    geoPoliticalStatus: "Non-Aligned",
    block: "None",
    culture: "Rural & Agrarian",
    hdi: "0.77",
  },
  {
    spin: "#96",
    name: "Grand Norvarsk",
    slug: "grand-norvarsk",
    people: "5M",
    government: "Absolute Monarchy",
    gdp: "$50B",
    economy: "Agriculture",
    military: "Large Army",
    area: "350 000 km2",
    geoPoliticalStatus: "Non-Aligned",
    block: "POF (Member)",
    culture: "Humiliation",
    hdi: "0.87",
  },
  {
    spin: "#97",
    name: "Makara",
    slug: "makara",
    people: "25M",
    government: "Clan Council",
    gdp: "$40B",
    economy: "Caravane routes",
    military: "No Army",
    area: "800 000 km2",
    geoPoliticalStatus: "Non-Aligned",
    block: "None",
    culture: "Reincarnation / being late",
    hdi: "0.55",
  },
  {
    spin: "#98",
    name: "Nervella",
    slug: "nervella",
    people: "550k",
    government: "Military Dictatorship",
    gdp: "7.5",
    economy: "Tax Haven",
    military: "Large Army",
    area: "250 000 km2",
    geoPoliticalStatus: "Non-Aligned",
    block: "SDA",
    culture: "Shamanism",
    hdi: "0.74",
    statNotes: [
      "Nervella began at 500k population and 0.79 HDI.",
      "Hospitals, ports, and housing raised HDI to 0.84 before the recruitment action.",
      "Recruiting Asteria's best soldiers and housing their families increased population by 10% to 550k, but caused a temporary -0.10 HDI settlement penalty.",
      "Current HDI is 0.74 and recovers by +0.01 per day until it returns to 0.84 once the families have settled.",
    ],
    actions: [
      {
        nation: "State of Nervella",
        type: "Economic + Human Development",
        action:
          "The State of Nervella announces the National Port, Housing, and Skilled Migration Program, centered on the expansion of Velkara and the construction of new urban districts, public housing, hospitals, technical schools, and port infrastructure. Alongside these developments, Nervella will introduce incentives for skilled migrants, laborers, engineers, and medical professionals to settle in the country, with priority given to sectors tied to maritime trade, logistics, healthcare, and national development. The government states that this initiative is intended to expand the population, strengthen the economy, and improve the long-term quality of life across the state.",
      },
      {
        nation: "Nervella",
        type: "Economic",
        action:
          "Under the protection of Sabrayana, the displaced State of Nervella establishes the World Restoration Bank as the first pillar of Project Restore. Open to all nations regardless of policy or alignment, the bank will provide reconstruction loans, anti-poverty development funding, emergency liquidity, and infrastructure finance to states damaged by war, disaster, or collapse. Structured through Nervella's tax haven and offshore financial model, the institution will also offer reserve storage, low-tax capital shelter, and international recovery funds, allowing Nervella to profit through fees, financial services, and capital inflows while positioning itself as a central force in rebuilding the world and reducing poverty. God bless the wheel.",
      },
      {
        nation: "Nervella",
        type: "Economic",
        action:
          "Nervella establishes the Velkara Radiological Stabilization Authority (VRSA), constructing secure coastal containment and research facilities to address hazardous remnants and environmental risks following recent events in Asteria. The authority will develop domestic expertise and implement strict internal safety protocols to ensure long-term stability and containment.",
      },
      {
        nation: "Nervella",
        type: "Military Expansion",
        action:
          "Nervella recruits the best soldiers in Asteria, offering free housing to the families of those that serve. This new regiment will be named 'The Asterian Special Elite Force'. This action aims to improve population and army size.",
      },
    ],
  },
  {
    spin: "#99",
    name: "Krakoslandia",
    slug: "krakoslandia",
    people: "2M",
    government: "Theocracy (Shaman)",
    gdp: "$60B",
    economy: "Tourism",
    military: "Medium Army",
    area: "50 000 km2",
    geoPoliticalStatus: "Non-Aligned",
    block: "None",
    culture: "Sky Symbols",
    hdi: "0.85",
  },
  {
    spin: "#100",
    name: "Wurland",
    slug: "wurland",
    people: "15M",
    government: "Guild State",
    gdp: "$200B",
    economy: "Entertainment",
    military: "Standard Army",
    area: "200 000 km2",
    geoPoliticalStatus: "Non-Aligned",
    block: "POF (Member)",
    culture: "Technology",
    hdi: "0.67",
  },
  {
    spin: "#101",
    name: "Urium",
    slug: "urium",
    people: "80M",
    government: "Shamanic Council",
    gdp: "$4.5T",
    economy: "Drone Logistics / Agriculture",
    military: "Continental Power",
    area: "600 000 km2",
    geoPoliticalStatus: "None",
    block: "POF (Leader)",
    culture: "Dog Sacralization / Stealth Culture",
    hdi: "0.83",
  },
];
