import type { NationStats } from "./index";

export type CanonNation = NationStats & {
  spin: string;
};

export const canonNations: CanonNation[] = [
  {
      spin: "#1",
      name: "Primis",
      slug: "primis",
      people: "25M",
      government: "Colony - Military Govt",
      gdp: "Unknown",
      economy: "Tech & Oil",
      military: "Large 5 / 11",
      area: "500 000 km2",
      geoPoliticalStatus: "Colony of Moravia",
      block: "Defence Accords",
      statNotes: [
        "Phase 2: + 1 Army"
      ],
    },
  {
      spin: "#2",
      name: "Melandia",
      slug: "melandia",
      people: "750M",
      government: "Monarchy",
      gdp: "Unknown",
      economy: "Geothermal / Gems",
      military: "Air Superpower 7 / 11",
      area: "6 000 000 km2",
      geoPoliticalStatus: "War (vs Lithuania)",
      block: "None",
    },
  {
      spin: "#3",
      name: "Isma",
      slug: "isma",
      people: "1M",
      government: "Fallen Empire",
      gdp: "Unknown",
      economy: "Finance / Gems - 🕊️",
      military: "None 0 / 11",
      area: "500 000 km2",
      geoPoliticalStatus: "War (vs Vladaria)",
      block: "None",
    },
  {
      spin: "#4",
      name: "Yoggy",
      slug: "yoggy",
      people: "60M",
      government: "Junta",
      gdp: "Unknown",
      economy: "Textiles / Minerals 🌊",
      military: "Naval Superpower 7 / 11",
      area: "900 000 km2",
      geoPoliticalStatus: "Hostile (vs Zandoro)",
      block: "None",
    },
  {
      spin: "#5",
      name: "Liberterra (Ourterra)",
      slug: "liberterra",
      people: "150M",
      government: "Democracy now Communist",
      gdp: "Unknown",
      economy: "Freshwater - 🗳️",
      military: "Small Defensive 2 / 11",
      area: "100 000 km2",
      geoPoliticalStatus: "Freeze (vs Imeria)",
      block: "Novus Ordo Mundi",
    },
  {
      spin: "#6",
      name: "Belvion",
      slug: "belvion",
      people: "80M",
      government: "Republic",
      gdp: "Unknown",
      economy: "Energy / Textiles",
      military: "Continental Power 9 / 11",
      area: "600 000 km2",
      geoPoliticalStatus: "War (vs Freelandia)",
      block: "None",
    },
  {
      spin: "#7",
      name: "Fredya",
      slug: "fredya",
      people: "400M",
      government: "Technocracy",
      gdp: "$2.5T",
      economy: "$2.5T Manuf. / 🔥 Fire god",
      military: "Medium 4 / 11",
      area: "400 000 km2",
      geoPoliticalStatus: "Techno-Magic",
      block: "None",
    },
  {
      spin: "#8",
      name: "Nordmere",
      slug: "nordmere",
      people: "30M",
      government: "Constitutional Monarchy",
      gdp: "$150B",
      economy: "$150B Green Economy -🌿",
      military: "Small 2 / 11",
      area: "400 000 km2",
      geoPoliticalStatus: "Rival (Shadow Conf.)",
      block: "Novus Ordo Mundi",
    },
  {
      spin: "#9",
      name: "Catomane",
      slug: "catomane",
      people: "50M",
      government: "Stratocracy",
      gdp: "$5T",
      economy: "$5T Innovation / 🔥 Fire god",
      military: "Special Forces 7 / 11",
      area: "400 000 km2",
      geoPoliticalStatus: "Tension (vs Omaleko)",
      block: "Novus Ordo Mundi",
      statNotes: [
        "Phase 2: No more / Border Tension"
      ],
    },
  {
      spin: "#10",
      name: "Dalgaristan",
      slug: "dalgaristan",
      people: "175M",
      government: "Socialist Republic",
      gdp: "$2T",
      economy: "$2T Surveillance",
      military: "Advanced 6 / 11",
      area: "900 000 km2",
      geoPoliticalStatus: "Former 🔴 War (vs URHNB)",
      block: "POF Alliance",
      statNotes: [
        "Phase 2: WAR OVER"
      ],
    },
  {
      spin: "#11",
      name: "N. Lights",
      slug: "northern-lights",
      people: "40M",
      government: "Ritualistic Kingdom",
      gdp: "$100B",
      economy: "$100B Pharma",
      military: "Continental Power 9 / 11",
      area: "800 000 km2",
      geoPoliticalStatus: "Dual Rituals",
      block: "None",
    },
  {
      spin: "#12",
      name: "Moradior",
      slug: "moradior",
      people: "175M",
      government: "Robotic Dominion",
      gdp: "$2.5T",
      economy: "$2.5T Robotics - 🦾",
      military: "Regional Power 8 / 11",
      area: "750 000 km2",
      geoPoliticalStatus: "War (vs Rei-Kai)",
      block: "Defence Accords",
      statNotes: [
        "Phase 2: Prepare for Sabrayana Invasion"
      ],
    },
  {
      spin: "#13",
      name: "Great Lithuania",
      slug: "great-lithuania",
      people: "60M",
      government: "Expansionist Republic",
      gdp: "$50B",
      economy: "$50B Healthcare - 🦅",
      military: "Expansionist 10 / 11",
      area: "1 000 000 km2",
      geoPoliticalStatus: "War (vs Melandia)",
      block: "None",
    },
  {
      spin: "#14",
      name: "Maronia",
      slug: "maronia",
      people: "100M",
      government: "Traditional Kingdom",
      gdp: "$700B",
      economy: "$700B Agriculture / 🏛️ Mythology",
      military: "Air Superpower 7 / 11",
      area: "9 000 000 km2",
      geoPoliticalStatus: "Freeze (vs Belvion)",
      block: "None",
    },
  {
      spin: "#15",
      name: "Daroille",
      slug: "daroille",
      people: "15M",
      government: "Corporate Confederation",
      gdp: "$3T",
      economy: "$3T Casinos - 💰",
      military: "Medium 4 / 11",
      area: "100 000 km2",
      geoPoliticalStatus: "Allied (Qashira)",
      block: "Novus Ordo Mundi",
    },
  {
      spin: "#16",
      name: "Torenza",
      slug: "torenza",
      people: "50M",
      government: "Authoritarian Republic",
      gdp: "$6T",
      economy: "$6T Space / Human",
      military: "Expansionist 10 / 11",
      area: "600 000 km2",
      geoPoliticalStatus: "Allied (Primis)",
      block: "Defence Accords",
    },
  {
      spin: "#17",
      name: "Imeria",
      slug: "imeria",
      people: "5M",
      government: "Colony - Feudal Warlords",
      gdp: "$400B",
      economy: "$400B Warlords",
      military: "Standard 3 / 11",
      area: "10 000 km2",
      geoPoliticalStatus: "Colony of Vienzerna",
      block: "None",
    },
  {
      spin: "#18",
      name: "Wonderia",
      slug: "wonderia",
      people: "80M",
      government: "Colony - Cybernetic Regency",
      gdp: "$400B",
      economy: "$400B Cybernetics - 🦾",
      military: "Cyber Hegemony / Cyberwarfare 11 / 11",
      area: "750 000 km2",
      geoPoliticalStatus: "Prot. of Yoggy",
      block: "None",
    },
  {
      spin: "#19",
      name: "B. Obrero",
      slug: "b-obrero",
      people: "750k",
      government: "Progressive Union",
      gdp: "$500M",
      economy: "$500M Church Tax",
      military: "Standard 3 / 11",
      area: "50 000 km2",
      geoPoliticalStatus: "PARIAH",
      block: "HATED BY ALL",
    },
  {
      spin: "#20",
      name: "Vienzerna",
      slug: "vienzerna",
      people: "125M",
      government: "Trade Empire",
      gdp: "$3.5T",
      economy: "$3.5T Guilds",
      military: "Expansionist 10 / 11",
      area: "750 000 km2",
      geoPoliticalStatus: "Colonizer",
      block: "None",
    },
  {
      spin: "#21",
      name: "Vladaria",
      slug: "vladaria",
      people: "5M",
      government: "Theocratic Kingdom",
      gdp: "$1B",
      economy: "$1B AI - 🦾 / Ditopism",
      military: "Standard 3 / 11",
      area: "200 000 km2",
      geoPoliticalStatus: "War (vs Isma)",
      block: "Royal Wedding alliance",
    },
  {
      spin: "#22",
      name: "Bernaland",
      slug: "bernaland",
      people: "5M",
      government: "Federal Republic",
      gdp: "$1B",
      economy: "$1B Robotics - 🗳️🦾",
      military: "Standard 3 / 11",
      area: "200 000 km2",
      geoPoliticalStatus: "Allied (Scopeople)",
      block: "Novus Ordo Mundi",
    },
  {
      spin: "#23",
      name: "Plesshurye",
      slug: "plesshurye",
      people: "500M",
      government: "Democratic Republic",
      gdp: "$6T",
      economy: "$6T Finance / Space",
      military: "Spatial Superpower 7 / 11",
      area: "800 000 km2",
      geoPoliticalStatus: "Exploration Culture",
      block: "None",
    },
  {
      spin: "#24",
      name: "Rei-Kai",
      slug: "rei-kai",
      people: "70M",
      government: "Fascist Empire",
      gdp: "$7T",
      economy: "$7T Biotech",
      military: "Advanced 6 / 11",
      area: "500 000 km2",
      geoPoliticalStatus: "War (vs Moradior)",
      block: "POF Alliance",
    },
  {
      spin: "#25",
      name: "Zharak-Ten",
      slug: "zharak-ten",
      people: "200M",
      government: "Maritime Democracy",
      gdp: "$500B",
      economy: "$500B Fish / Ent. / 🌊 / Shamanic",
      military: "Advanced 6 / 11",
      area: "900 000 km2",
      geoPoliticalStatus: "Allied (Navatonia)",
      block: "Novus Ordo Mundi",
    },
  {
      spin: "#26",
      name: "Zottegem",
      slug: "zottegem",
      people: "30M",
      government: "Financial Oligarchy",
      gdp: "$40B",
      economy: "$40B Shadow Bank - 💰",
      military: "Small Defensive 2 / 11",
      area: "400 000 km2",
      geoPoliticalStatus: "Allied (Moradior)",
      block: "Defence Accords",
    },
  {
      spin: "#27",
      name: "Fish State",
      slug: "fish-state",
      people: "25M",
      government: "Naval Junta",
      gdp: "$400B",
      economy: "$400B Maritime 🌊",
      military: "Large 5 / 11",
      area: "300 000 km2",
      geoPoliticalStatus: "War (vs Imeria)",
      block: "None",
    },
  {
      spin: "#28",
      name: "Anuruthor",
      slug: "anuruthor",
      people: "40M",
      government: "Protectorate",
      gdp: "$1T",
      economy: "$1T Heavy Industry",
      military: "Small Defensive 2 / 11",
      area: "500 000 km2",
      geoPoliticalStatus: "Rival (vs Rei-Kai)",
      block: "None",
    },
  {
      spin: "#29",
      name: "Shadow Conf.",
      slug: "shadow-conf",
      people: "175M",
      government: "Pirate Confederation",
      gdp: "$1.5T",
      economy: "$1.5T Piracy 🌊",
      military: "Large 5 / 11",
      area: "500 000 km2",
      geoPoliticalStatus: "Rival (vs Nordmere)",
      block: "None",
    },
  {
      spin: "#30",
      name: "Tunguska",
      slug: "tunguska",
      people: "750k",
      government: "Colony - Clan Council",
      gdp: "$200B",
      economy: "$200B Ritual Tour.",
      military: "Small Defensive 2 / 11",
      area: "175 000 km2",
      geoPoliticalStatus: "Colony of U. Tribes",
      block: "Novus Ordo Mundi",
    },
  {
      spin: "#31",
      name: "C. Ranchers",
      slug: "c-ranchers",
      people: "10M",
      government: "Anarchist Commune",
      gdp: "$5B",
      economy: "$5B Ranching - ☢️",
      military: "Regional Influence Army 8 / 11",
      area: "100 000 km2",
      geoPoliticalStatus: "Anarchist",
      block: "Royal Wedding alliance",
    },
  {
      spin: "#32",
      name: "Solaria",
      slug: "solaria",
      people: "100M",
      government: "Federal Empire",
      gdp: "$9T",
      economy: "$9T Shadow Banking",
      military: "Large 5 / 11",
      area: "60 000 km2",
      geoPoliticalStatus: "Defense Pact (Dalgaristan)",
      block: "POF Alliance",
      statNotes: [
        "Phase 2: -1 HDI / +1 GDP"
      ],
    },
  {
      spin: "#33",
      name: "Skressia",
      slug: "skressia",
      people: "15M",
      government: "Drone Republic",
      gdp: "$50B",
      economy: "$50B Drones",
      military: "Standard 3 / 11",
      area: "1 000 km2",
      geoPoliticalStatus: "War (vs Azur Axis)",
      block: "None",
    },
  {
      spin: "#34",
      name: "Moravia",
      slug: "great-moravia",
      people: "900M",
      government: "Cyber-Dictatorship",
      gdp: "$8T",
      economy: "$8T Cyber / Loans - 🦾",
      military: "WORLD MENACE 11 / 11",
      area: "3 000 000 km2",
      geoPoliticalStatus: "War (vs Golden Land)",
      block: "Defence Accords)",
      statNotes: [
        "Phase 2: Next turn can attack Zubrossya"
      ],
    },
  {
      spin: "#35",
      name: "ABOC",
      slug: "aboc",
      people: "700M",
      government: "Decentralized Union",
      gdp: "$1T",
      economy: "$1T Waste Mgt - ☢️",
      military: "None 0 / 11",
      area: "90 000 km2",
      geoPoliticalStatus: "Trade (Rei-Kai)",
      block: "None",
    },
  {
      spin: "#36",
      name: "Voidia",
      slug: "voidia",
      people: "40M",
      government: "Agrarian Monarchy",
      gdp: "$500B",
      economy: "$500B Agriculture - Alien Cult",
      military: "Continental Power 9 / 11",
      area: "200 000 km2",
      geoPoliticalStatus: "Freeze (vs Maronia)",
      block: "None",
    },
  {
      spin: "#37",
      name: "Runonno",
      slug: "runonno",
      people: "25M",
      government: "Military Superstate",
      gdp: "$1T",
      economy: "$1T Security - ☢️",
      military: "Land Superpower 7 / 11",
      area: "800 000 km2",
      geoPoliticalStatus: "VS EVERYONE",
      block: "None",
    },
  {
      spin: "#38",
      name: "Azur Axis",
      slug: "azur-axis",
      people: "40M",
      government: "AI Corporatocracy",
      gdp: "$900B",
      economy: "$900B Shell / AI",
      military: "Small Defensive 2 / 11",
      area: "500 000 km2",
      geoPoliticalStatus: "War (vs Skressia)",
      block: "None",
    },
  {
      spin: "#39",
      name: "Freelandia",
      slug: "freelandia",
      people: "15M",
      government: "Industrial Republic",
      gdp: "$900B",
      economy: "$900B Heavy Ind.",
      military: "Regional Power 8 / 11",
      area: "350 000 km2",
      geoPoliticalStatus: "War (vs Belvion)",
      block: "None",
    },
  {
      spin: "#40",
      name: "Aragon",
      slug: "40-aragon",
      people: "80M",
      government: "Media Monarchy",
      gdp: "$3T",
      economy: "$3T Entertainment - 💰",
      military: "Continental Power 9 / 11",
      area: "350 000 km2",
      geoPoliticalStatus: "Allied (Whiterun)",
      block: "Novus Ordo Mundi",
    },
  {
      spin: "#41",
      name: "Scopeople",
      slug: "scopeople",
      people: "30M",
      government: "Tribal Kingdom",
      gdp: "$1B",
      economy: "$1B Local Trade",
      military: "None 0 / 11",
      area: "175 000 km2",
      geoPoliticalStatus: "Allied (Bernaland)",
      block: "Novus Ordo Mundi",
    },
  {
      spin: "#42",
      name: "Aura Sancta",
      slug: "aura-sancta",
      people: "500M",
      government: "Empire",
      gdp: "$10T",
      economy: "$10T Tourism",
      military: "WORLD POLICE 11 / 11",
      area: "12 000 000 km2",
      geoPoliticalStatus: "World Peace Doctrine",
      block: "Novus Ordo Mundi",
    },
  {
      spin: "#43",
      name: "Navatonia",
      slug: "navatonia",
      people: "300M",
      government: "Shamanic Republic",
      gdp: "$3T",
      economy: "$3T Mining / Shaman",
      military: "Regional Power 8 / 11",
      area: "750 000 km2",
      geoPoliticalStatus: "Allied (Zharak-Ten)",
      block: "Novus Ordo Mundi",
    },
  {
      spin: "#44",
      name: "Abolitionist G.",
      slug: "abolitionist-g",
      people: "200M",
      government: "Guild Republic",
      gdp: "$9T",
      economy: "$9T Black Market",
      military: "Continental Power 9 / 11",
      area: "75 000 km2",
      geoPoliticalStatus: "PARIAH",
      block: "HATED BY ALL",
      statNotes: [
        "Phase 2: Supports Moravia"
      ],
    },
  {
      spin: "#45",
      name: "Golden Land",
      slug: "golden-land",
      people: "25M",
      government: "Mercantile Democracy",
      gdp: "$3T",
      economy: "$3T Grey Market",
      military: "Continental Power 9 / 11",
      area: "125 000 km2",
      geoPoliticalStatus: "War (vs Moravia)",
      block: "None",
    },
  {
      spin: "#46",
      name: "Whiterun",
      slug: "whiterun",
      people: "30M",
      government: "Academic Republic",
      gdp: "$600B",
      economy: "$600B Education",
      military: "Medium Army 4 / 11",
      area: "300 000 km2",
      geoPoliticalStatus: "Allied (Aragon)",
      block: "Novus Ordo Mundi",
    },
  {
      spin: "#47",
      name: "United Tribes",
      slug: "united-tribes",
      people: "10M",
      government: "Tribal Confederation",
      gdp: "$400B",
      economy: "$400B Green Econ - 🌿",
      military: "Medium Army 4 / 11",
      area: "200 000 km2",
      geoPoliticalStatus: "Parent of Tunguska",
      block: "Novus Ordo Mundi",
    },
  {
      spin: "#48",
      name: "Icelania",
      slug: "icelania",
      people: "125M",
      government: "Pharma Republic",
      gdp: "$14T",
      economy: "$14T Pharma / Manuf",
      military: "Advanced Army 6 / 11",
      area: "400 000 km2",
      geoPoliticalStatus: "Rival (Catomane)",
      block: "None",
    },
  {
      spin: "#49",
      name: "Omaleko",
      slug: "omaleko",
      people: "400M",
      government: "Social Commonwealth",
      gdp: "$12T",
      economy: "$12T Oil / Auto",
      military: "Standard 3 / 11",
      area: "1 000 000 km2",
      geoPoliticalStatus: "Tension (Catomane)",
      block: "Defence Accords",
      statNotes: [
        "Phase 2: No more / Border Tension"
      ],
    },
  {
      spin: "#50",
      name: "Rootbeerism",
      slug: "rootbeerism",
      people: "80M",
      government: "Corporate State",
      gdp: "$1T",
      economy: "$1T Call Centers",
      military: "Special Forces 7 / 11",
      area: "200 000 km2",
      geoPoliticalStatus: "Trade (Runonno)",
      block: "None",
    },
  {
      spin: "#51",
      name: "Dowenia",
      slug: "dowenia",
      people: "1.2B",
      government: "Crypto-Anarchy",
      gdp: "$5T",
      economy: "$5T Crypto / Bank",
      military: "None 0 / 11",
      area: "1 000 000 km2",
      geoPoliticalStatus: "Underground Networks",
      block: "None",
    },
  {
      spin: "#52",
      name: "Schizolandia",
      slug: "schizolandia",
      people: "100k",
      government: "People's Union",
      gdp: "$50M",
      economy: "$50M Cultural / Druidic - 🌿",
      military: "Small Defensive 2 / 11",
      area: "40 000 km2",
      geoPoliticalStatus: "Hostile (Moravia)",
      block: "Novus Ordo Mundi",
    },
  {
      spin: "#53",
      name: "Lumenie",
      slug: "lumenie",
      people: "5M",
      government: "Colony - Nomadics",
      gdp: "$100M",
      economy: "$100M AI / Robots - 🦾",
      military: "Standard 3 / 11",
      area: "125 000 km2",
      geoPoliticalStatus: "Prot. of B. Obrero",
      block: "Novus Ordo Mundi",
    },
  {
      spin: "#54",
      name: "URHNB",
      slug: "urhnb",
      people: "15M",
      government: "United Republics",
      gdp: "$100B",
      economy: "$100B Defense",
      military: "Continental Power 9 / 11",
      area: "900 000 km2",
      geoPoliticalStatus: "Former 🔴 War (vs Dalgaristan)",
      block: "None",
      statNotes: [
        "Phase 2: WAR OVER"
      ],
    },
  {
      spin: "#55",
      name: "Black Cult",
      slug: "black-cult",
      people: "250M",
      government: "Expansionist Theocracy",
      gdp: "$7T",
      economy: "$7T Energy / Manuf",
      military: "Expansionist 10 / 11",
      area: "500 000 km2",
      geoPoliticalStatus: "PARIAH",
      block: "HATED BY ALL",
    },
  {
      spin: "#56",
      name: "G. Celtia",
      slug: "greater-celtia",
      people: "90M",
      government: "Clan Empire",
      gdp: "$30T",
      economy: "$30T Cloning - 🦾",
      military: "Air Superpower 7 / 11",
      area: "400 000 km2",
      geoPoliticalStatus: "Rival (Solaria)",
      block: "None",
    },
  {
      spin: "#57",
      name: "Sabrayana",
      slug: "sabrayana",
      people: "2.5B",
      government: "Magical Empire",
      gdp: "$12T",
      economy: "$12T Magic Cards - Shamanic",
      military: "Expansionist Power",
      area: "12 000 000 km2",
      geoPoliticalStatus: "Allied (Melandia)",
      block: "None",
    },
  {
      spin: "#58",
      name: "Aesyl",
      slug: "aesyl",
      people: "7M",
      government: "Independent Commune",
      gdp: "$150B",
      economy: "$150B Wooden Chairs - 🕊️",
      military: "Advanced Army 6 / 11",
      area: "40 000 km2",
      geoPoliticalStatus: "Guaranteed by ALL",
      block: "Global Arbiter (HQ)",
    },
  {
      spin: "#59",
      name: "Techlandia",
      slug: "techlandia",
      people: "60M",
      government: "Technocratic State",
      gdp: "$8T",
      economy: "$8T Space / Nuclear",
      military: "Spatial Superpower 7 / 11",
      area: "500 000 km2",
      geoPoliticalStatus: "Allied (Navatonia)",
      block: "Novus Ordo Mundi",
    },
  {
      spin: "#60",
      name: "Black League",
      slug: "black-league",
      people: "150M",
      government: "Forced Labor Union",
      gdp: "$5T",
      economy: "$5T Forced Labor - 🦅",
      military: "Land Superpower 7 / 11",
      area: "800 000 km2",
      geoPoliticalStatus: "War (vs Belvion)",
      block: "None",
    },
  {
      spin: "#61",
      name: "Norasia",
      slug: "norasia",
      people: "250k",
      government: "Republic",
      gdp: "$20B",
      economy: "$20B Salt Monopoly - 💰",
      military: "Small Defensive 2 / 11",
      area: "75 000 km2",
      geoPoliticalStatus: "Allied (Dalgaristan)",
      block: "None",
      statNotes: [
        "Phase 2: Inflige - 10 GDP si attack zubrosya"
      ],
    },
  {
      spin: "#62",
      name: "Rootberia",
      slug: "rootberia",
      people: "3M",
      government: "Gambling State",
      gdp: "$30B",
      economy: "$30B Gambling - 💰",
      military: "Small Defensive 2 / 11",
      area: "40 000 km2",
      geoPoliticalStatus: "Trade (Voidia)",
      block: "None",
    },
  {
      spin: "#63",
      name: "Solandria",
      slug: "solandria",
      people: "15M",
      government: "Colony",
      gdp: "$700B",
      economy: "$700B Cybernetics / 🔥 Fire god",
      military: "Standard 3 / 11",
      area: "250 000 km2",
      geoPoliticalStatus: "Colony of Sabrayana",
      block: "None",
    },
  {
      spin: "#64",
      name: "Traguera",
      slug: "traguera",
      people: "5M",
      government: "Auth, Republic",
      gdp: "$15B",
      economy: "$15B Addiction Food",
      military: "Standard 3 / 11",
      area: "400 000 km2",
      geoPoliticalStatus: "Allied (Golden Land)",
      block: "None",
    },
  {
      spin: "#65",
      name: "Dravencia",
      slug: "dravencia",
      people: "150M",
      government: "Fascism",
      gdp: "$12T",
      economy: "$12T Rare Wood - 🦅",
      military: "Large Army 5 / 11",
      area: "3 000 000 km2",
      geoPoliticalStatus: "Allied (Anuruthor)",
      block: "None",
    },
  {
      spin: "#66",
      name: "Zhiva-Zarina",
      slug: "zhiva-zarina",
      people: "5M",
      government: "Confederation",
      gdp: "$90B",
      economy: "$90B Health / Auto - 🕊️",
      military: "Small Defensive 2 / 11",
      area: "450 000 km2",
      geoPoliticalStatus: "Trade (Belvion)",
      block: "None",
    },
  {
      spin: "#67",
      name: "Qashira",
      slug: "qashira",
      people: "10M",
      government: "Parliamentary Democracy",
      gdp: "$900B",
      economy: "$900B Education - 🗳️",
      military: "Regional Power 8 / 11",
      area: "400 000 km2",
      geoPoliticalStatus: "Allied (Daroille)",
      block: "Novus Ordo Mundi",
      statNotes: [
        "Phase 2: 10 milions refugees"
      ],
    },
  {
      spin: "#68",
      name: "Karakum",
      slug: "karakum",
      people: "3M",
      government: "Communist Republic",
      gdp: "$4B",
      economy: "$4B Hydropower - 🌿",
      military: "None 0 / 11",
      area: "300 000 km2",
      geoPoliticalStatus: "Prot. (B. Obrero)",
      block: "Novus Ordo Mundi",
    },
  {
      spin: "#69",
      name: "Zandoro",
      slug: "zandoro",
      people: "4M",
      government: "Military Dictatorship",
      gdp: "$110B",
      economy: "$110B Art / Bananas",
      military: "Large Army 5 / 11",
      area: "175 000 km2",
      geoPoliticalStatus: "Hostile (Yoggy)",
      block: "None",
      statNotes: [
        "Phase 2: No more art +1 gdp + 1 army"
      ],
    },
  {
      spin: "#70",
      name: "Zubrossya",
      slug: "zubrossya",
      people: "15M",
      government: "Communist Social Republic",
      gdp: "$500B",
      economy: "$500B Global Data - 🦾",
      military: "Advanced Army 6 / 11",
      area: "450 000 km2",
      geoPoliticalStatus: "Tension (Moravia)",
      block: "None",
    },
  {
      spin: "#71",
      name: "Yerna",
      slug: "yerna",
      people: "250M",
      government: "Fascist Republic",
      gdp: "$9T",
      economy: "$9T Lit. / Subscriptions - 🦅",
      military: "Land Superpower 7 / 11",
      area: "1 000 000 km2",
      geoPoliticalStatus: "Influence (Moradior)",
      block: "Defence Accords",
    },
  {
      spin: "#72",
      name: "Katzash",
      slug: "katzash",
      people: "50M",
      government: "Federal Democracy",
      gdp: "$1T",
      economy: "$1T Paper / Innov. - 🗳️",
      military: "Expansionist 10 / 11",
      area: "800 000 km2",
      geoPoliticalStatus: "Allied (Moravia)",
      block: "Defence Accords",
      statNotes: [
        "Phase 2: Expend 1 M km2"
      ],
    },
  {
      spin: "#73",
      name: "Syrenthia",
      slug: "syrenthia",
      people: "250k",
      government: "Colony - Warrior Council",
      gdp: "$40B",
      economy: "$40B Mercenaries - 🦾",
      military: "Special Forces 7 / 11",
      area: "60 000 km2",
      geoPoliticalStatus: "Prot. of Moravia",
      block: "Defence Accords",
    },
  {
      spin: "#74",
      name: "Xentael",
      slug: "xentael",
      people: "7M",
      government: "Communist State",
      gdp: "$150B",
      economy: "$150B Nuc. Waste - ☢️",
      military: "Medium Army 4 / 11",
      area: "150 000 km2",
      geoPoliticalStatus: "Trade (Rei-Kai)",
      block: "None",
    },
  {
      spin: "#75",
      name: "Ditopia",
      slug: "ditopia",
      people: "1M",
      government: "Theocracy",
      gdp: "$90B",
      economy: "$90B Rails / Holy - 🕊️ / Ditopism",
      military: "Advanced Army 6 / 11",
      area: "20 000 km2",
      geoPoliticalStatus: "Non-Aligned",
      block: "Global Arbiter",
    },
  {
      spin: "#76",
      name: "Veltaris",
      slug: "veltaris",
      people: "125M",
      government: "Absolute Monarchy",
      gdp: "$18T",
      economy: "$18T Monopolies - 💰",
      military: "WORLD ARBITER 11 / 11",
      area: "1 000 000 km2",
      geoPoliticalStatus: "Non-Aligned",
      block: "Global Arbiter",
    },
  {
      spin: "#77",
      name: "Santa Kova",
      slug: "santa-kova",
      people: "115 M",
      government: "Confederation",
      gdp: "$2T",
      economy: "$2T - Literrature and Voice acting",
      military: "Naval Superpower 7 / 11",
      area: "1 000 000 km2",
      geoPoliticalStatus: "South Defence Accords",
      block: "Defence Accords",
    },
  {
      spin: "#78",
      name: "ShieldHolm",
      slug: "shieldholm",
      people: "10 M",
      government: "Auth, Republic",
      gdp: "$500B",
      economy: "$500B - Troll farm - Cloning",
      military: "Medium Army 4 / 11",
      area: "750 000 km2",
      geoPoliticalStatus: "Non-Aligned",
      block: "None",
    },
  {
      spin: "#79",
      name: "Kingdom of Maple",
      slug: "kingdom-of-maple",
      people: "30 M",
      government: "Monarchy",
      gdp: "$900B",
      economy: "$900B - Oil / Gas and Anime",
      military: "Army Alliances 7 / 11",
      area: "900 000 km2",
      geoPoliticalStatus: "POF Alliance",
      block: "POF Alliance",
    },
  {
      spin: "#80",
      name: "Britonia",
      slug: "britonia",
      people: "5 M",
      government: "Military Dictatorship",
      gdp: "$90B",
      economy: "$90B - Corruption",
      military: "Standard 3 / 11",
      area: "3 000 000 km2",
      geoPoliticalStatus: "",
      block: "Defence Accords",
    },
  {
      spin: "#81",
      name: "Chungun Republic",
      slug: "chungun-republic",
      people: "50 M",
      government: "Presidential Republic",
      gdp: "$900B",
      economy: "$900B - Healthcare",
      military: "Medium Army 4 / 11",
      area: "500 000 km2",
      geoPoliticalStatus: "",
      block: "Defence Accords",
    },
  {
      spin: "#82",
      name: "Cordolia",
      slug: "cordolia",
      people: "30 M",
      government: "Communism",
      gdp: "$1T",
      economy: "$1 T - Cybernetics and Shadow trade",
      military: "Cybernetics Army 7 / 11",
      area: "3 000 000 km2",
      geoPoliticalStatus: "Non-Aligned",
      block: "None",
    },
  {
      spin: "#83",
      name: "Golden River",
      slug: "golden-river-confederation",
      people: "7 M",
      government: "Confederation",
      gdp: "$8T",
      economy: "$8 T - Bananas and Maritime trade",
      military: "Naval Superpower 7 / 11",
      area: "450 000 km2",
      geoPoliticalStatus: "POF Alliance",
      block: "POF Alliance",
    },
  {
      spin: "#84",
      name: "Great Valoria",
      slug: "great-valoria",
      people: "25 M",
      government: "Shamanic Council",
      gdp: "$500B",
      economy: "$500 B - Church tax",
      military: "Medium Army 4 / 11",
      area: "600 000 km2",
      geoPoliticalStatus: "Non-Aligned",
      block: "None",
    },
  {
      spin: "#85",
      name: "Royal Guild of Jamland",
      slug: "royal-guild-of-jamland",
      people: "7 M",
      government: "Merchant guild Kingdom",
      gdp: "$300B",
      economy: "$300 B - Manufacturing",
      military: "Small Defensive 2 / 11",
      area: "300 000 km2",
      geoPoliticalStatus: "South Defence Accords",
      block: "Defence Accords",
    },
  {
      spin: "#86",
      name: "United Geats",
      slug: "united-geats",
      people: "200 M",
      government: "Democracy",
      gdp: "$10T",
      economy: "$10T - Agriculture & Textile",
      military: "Large Army 5 / 11",
      area: "6 000 000 km2",
      geoPoliticalStatus: "Non-Aligned",
      block: "None",
    },
  {
      spin: "#87",
      name: "Geometrizan",
      slug: "geometrizan",
      people: "2M",
      government: "Democracy",
      gdp: "$100B",
      economy: "$100 B - Tourist Exploitation",
      military: "Standard 3 / 11",
      area: "60 000 km2",
      geoPoliticalStatus: "",
      block: "POF Alliance",
    },
  {
      spin: "#88",
      name: "Union Of Man and Nature",
      slug: "union-of-man-and-nature",
      people: "7 M",
      government: "Colony -",
      gdp: "$300B",
      economy: "$300 B - Hydropower",
      military: "Medium Army 4 / 11",
      area: "900 000 km2",
      geoPoliticalStatus: "Colony - Plesshurye",
      block: "Novus Ordo Mundi",
    },
  {
      spin: "S2 #1",
      name: "Aagyr",
      slug: "aagyr",
      people: "25 000 000",
      government: "Presidential Republic",
      gdp: "$500B",
      economy: "Jewelry craft",
      military: "Basic Army 5/10",
      area: "300 000 km2",
      geoPoliticalStatus: "Diplo Isolation",
      block: "Demonbound",
      culture: "Never Smiling",
      hdi: "0.84",
      statNotes: [
        "Leader Traits: Vengeful +2 Mil",
        "Localisation: South Fang",
        "Influence: 5.0",
        "Note: 5.5"
      ],
    },
  {
      spin: "S2 #2",
      name: "Grunewald",
      slug: "grunewald",
      people: "250 000 000",
      government: "Auth. Republic",
      gdp: "$2.5T",
      economy: "Hydropower / Cows",
      military: "Basic Army 5/10",
      area: "1 000 000 km2",
      geoPoliticalStatus: "Long peace",
      block: "Demonbound",
      culture: "Nap / Guild order",
      hdi: "0.80",
      statNotes: [
        "Leader Traits: Leper -2 HDI",
        "Localisation: North Fang",
        "Influence: 6.0",
        "Note: 7"
      ],
    },
  {
      spin: "S2 #3",
      name: "Weak Empire",
      slug: "weak-empire",
      people: "50 000 000",
      government: "High Tribal Kingdom",
      gdp: "$900B",
      economy: "Manuf / Desalinisation",
      military: "Organized Army 6/10",
      area: "900 000 km2",
      geoPoliticalStatus: "Ember Industry",
      block: "Demonbound",
      culture: "Elder Respect / Shaming",
      hdi: "0.62",
      statNotes: [
        "Leader Traits: Beautiful +1 HDI",
        "Localisation: Red Ear",
        "Influence: 5.0",
        "Note: 6"
      ],
    },
  {
      spin: "S2 #4",
      name: "Rōzurando shū",
      slug: "rozurando-shu",
      people: "80 000 000",
      government: "Presidential Republic",
      gdp: "$9T",
      economy: "Critical Ress / Bananas",
      military: "Organized Army 6/10",
      area: "600 000 km2",
      geoPoliticalStatus: "Iron Stability",
      block: "Resilient",
      culture: "Matriarchal",
      hdi: "0.93",
      statNotes: [
        "Leader Traits: Naive -2 Military",
        "Localisation: Feastwater",
        "Influence: 8.0",
        "Note: 7.333333333"
      ],
    },
  {
      spin: "S2 #5",
      name: "Vulcan",
      slug: "vulcan",
      people: "110 000 000",
      government: "Plutocracy",
      gdp: "$9T",
      economy: "Mining",
      military: "Global Military (Land/Air) 9/10",
      area: "60 000 km2",
      geoPoliticalStatus: "Strategic Hesitation",
      block: "Resilient",
      culture: "Underground",
      hdi: "0.92",
      statNotes: [
        "Leader Traits: Zealous +2 Mil",
        "Localisation: Red Ear",
        "Influence: 8.0",
        "Note: 7.166666667"
      ],
    },
  {
      spin: "S2 #6",
      name: "Autronia",
      slug: "autronia",
      people: "9 000 000",
      government: "Constitutional Monarchy",
      gdp: "$600B",
      economy: "Heavy Industry",
      military: "No Army 0/10",
      area: "40 000 km2",
      geoPoliticalStatus: "Economic Collapse",
      block: "Demonbound",
      culture: "Cybernetic",
      hdi: "0.6",
      statNotes: [
        "Leader Traits: Quick +1 GDP",
        "Localisation: Seas of tears",
        "Influence: 3.0",
        "Note: 3.5"
      ],
    },
  {
      spin: "S2 #7",
      name: "Invictus Realm",
      slug: "invictus-realm",
      people: "60 000 000",
      government: "Absolute Monarchy",
      gdp: "$1T",
      economy: "Scientific Res / Coffee",
      military: "Elite Army 7/10",
      area: "500 000 km2",
      geoPoliticalStatus: "Steady Growth",
      block: "Resilient",
      culture: "Authorit. / Scientific",
      hdi: "0.96",
      statNotes: [
        "Leader Traits: Imbecile -3 GDP",
        "Localisation: North Fang",
        "Influence: 6.0",
        "Note: 6.833333333"
      ],
    },
  {
      spin: "S2 #8",
      name: "Yoyleland",
      slug: "yoyleland",
      people: "2 000 000",
      government: "City- State",
      gdp: "$15B",
      economy: "Beers",
      military: "Civil Guard 1/10",
      area: "20 000 km2",
      geoPoliticalStatus: "Infernal Surge",
      block: "Demonbound",
      culture: "Hedonistic",
      hdi: "0.75",
      statNotes: [
        "Leader Traits: Fecund +2 Pop",
        "Localisation: Nosecrest",
        "Influence: 2.0",
        "Note: 2.5"
      ],
    },
  {
      spin: "S2 #9",
      name: "Intdocryn",
      slug: "intdocryn",
      people: "4 000 000",
      government: "Technocracy",
      gdp: "$500B",
      economy: "Financial Services +1 GDP",
      military: "Basic Army 5/10",
      area: "150 000 km2",
      geoPoliticalStatus: "Internal Revolt",
      block: "Demonbound",
      culture: "Ultra Surveillance",
      hdi: "0.76",
      statNotes: [
        "Leader Traits: Quick +1 GDP",
        "Localisation: Seas of tears",
        "Influence: 4.0",
        "Note: 5"
      ],
    },
  {
      spin: "S2 #10",
      name: "Belvaria",
      slug: "belvaria",
      people: "60 000 000",
      government: "Communism",
      gdp: "$600B",
      economy: "Paper / Heavy Ind",
      military: "Regional Military (Land) 8/10",
      area: "800 000 km2",
      geoPoliticalStatus: "Blood Economy",
      block: "Demonbound",
      culture: "Shaman / Storytell, Oral",
      hdi: "0.62",
      statNotes: [
        "Leader Traits: Deceitful -2 HDI",
        "Localisation: Twin Diadems",
        "Influence: 7.0",
        "Note: 6.666666667"
      ],
    },
  {
      spin: "S2 #11",
      name: "Trivarya",
      slug: "trivarya",
      people: "10 000 000",
      government: "Communism",
      gdp: "$700B",
      economy: "Yogurt Flavoring",
      military: "Elite Army 7/10",
      area: "450 000 km2",
      geoPoliticalStatus: "Ressource Burn",
      block: "Demonbound",
      culture: "Leader Worshipping",
      hdi: "0.65",
      statNotes: [
        "Leader Traits: Schemer +1 GDP",
        "Localisation: Seas of tears",
        "Influence: 3.0",
        "Note: 5.166666667"
      ],
    },
  {
      spin: "S2 #12",
      name: "Atomicmixiz",
      slug: "atomicmixiz",
      people: "2 000 000",
      government: "Fed. Republic",
      gdp: "$500M",
      economy: "Road Construction",
      military: "Organized Army 6/10",
      area: "100 000 km2",
      geoPoliticalStatus: "Hellfleet Naval Sup. Feastwater",
      block: "Demonbound",
      culture: "Ascetic",
      hdi: "0.91",
      statNotes: [
        "Leader Traits: Bastard - No Malus Republic",
        "Localisation: Feastwater",
        "Influence: 3.0",
        "Note: 4"
      ],
    },
  {
      spin: "S2 #13",
      name: "Ayyutit",
      slug: "ayyutit",
      people: "600 000 000",
      government: "Council of 100 Clans",
      gdp: "$9T",
      economy: "Security / Pharma / Hairstylist",
      military: "Elite Army 7/10",
      area: "600 000 km2",
      geoPoliticalStatus: "Dark Pact Trade",
      block: "Demonbound",
      culture: "Desert / Superstitious / Utopian",
      hdi: "0.42",
      statNotes: [
        "Leader Traits: Calm +1 HDI",
        "Localisation: Red Ear",
        "Influence: 7.0",
        "Note: 7"
      ],
    },
  {
      spin: "S2 #14",
      name: "Federal",
      slug: "federal",
      people: "1 700 000 000",
      government: "Fascism",
      gdp: "$20T",
      economy: "Agri / Lobby / Lux. Cruise",
      military: "Global Military (Naval/Air) 9/10",
      area: "6 000 000 km2",
      geoPoliticalStatus: "Ember Industry",
      block: "Demonbound",
      culture: "Medicine / Scholars / Fraternity",
      hdi: "0.92",
      statNotes: [
        "Leader Traits: Strategist +3 Military",
        "Localisation: Twin Diadems",
        "Influence: 9.0",
        "Note: 9.333333333"
      ],
    },
  {
      spin: "S2 #15",
      name: "Aurizhan",
      slug: "aurizhan",
      people: "500 000",
      government: "Communism",
      gdp: "$750M",
      economy: "Golden Rice",
      military: "Basic Army 5/10",
      area: "125 000 km2",
      geoPoliticalStatus: "Crimson Mobilization",
      block: "Demonbound",
      culture: "Vegan",
      hdi: "0.96",
      statNotes: [
        "Leader Traits: Just +2 HDI",
        "Localisation: South Fang",
        "Influence: 3.0",
        "Note: 3.833333333"
      ],
    },
  {
      spin: "S2 #16",
      name: "Qamilandia",
      slug: "qamilandia",
      people: "7 000 000",
      government: "Presidential Republic",
      gdp: "$1T",
      economy: "Elder's Care",
      military: "Elite Army 7/10",
      area: "900 000 km2",
      geoPoliticalStatus: "Infernal Surge",
      block: "Demonbound",
      culture: "Anti Science -1 HDI",
      hdi: "0.59",
      statNotes: [
        "Leader Traits: Temperate +1 GDP",
        "Localisation: Quiet Reach",
        "Influence: 5.0",
        "Note: 5.666666667"
      ],
    },
  {
      spin: "S2 #17",
      name: "Bennia",
      slug: "bennia",
      people: "1 000 000",
      government: "Corporate State",
      gdp: "$10B",
      economy: "Gambling",
      military: "Local Militia 3/10",
      area: "60 000 km2",
      geoPoliticalStatus: "Hellmouth Risk",
      block: "Demonbound",
      culture: "Pacifist",
      hdi: "0.55",
      statNotes: [
        "Leader Traits: Dwarf -1 HDI",
        "Localisation: Quiet Reach",
        "Influence: 2.0",
        "Note: 2.666666667"
      ],
    },
  {
      spin: "S2 #18",
      name: "Arcinia",
      slug: "arcinia",
      people: "115 000 000",
      government: "Auth. Republic",
      gdp: "$150B",
      economy: "Garbage / Street Food",
      military: "No Army 0/10",
      area: "900 000 km2",
      geoPoliticalStatus: "Moral Unity",
      block: "Resilient",
      culture: "Forest / Mountain clans",
      hdi: "0.28",
      statNotes: [
        "Leader Traits: Murderer -3 HDI",
        "Localisation: Red Ear",
        "Influence: 3.0",
        "Note: 3.833333333"
      ],
    },
  {
      spin: "S2 #19",
      name: "Forgovia",
      slug: "forgovia",
      people: "100 000",
      government: "Absolute Monarchy",
      gdp: "$15B",
      economy: "Top University",
      military: "Civil Guard 1/10",
      area: "10 000 km2",
      geoPoliticalStatus: "Population Drain",
      block: "Demonbound",
      culture: "Road Rage",
      hdi: "0.98",
      statNotes: [
        "Leader Traits: Generous +2 HDI",
        "Localisation: Nosecrest",
        "Influence: 5.0",
        "Note: 3.333333333"
      ],
    },
  {
      spin: "S2 #20",
      name: "Ranak",
      slug: "ranak",
      people: "80 000 000",
      government: "Absolute Monarchy",
      gdp: "$1T",
      economy: "Weeding Venues / Mercenaries",
      military: "Organized Army 6/10",
      area: "300 000 km2",
      geoPoliticalStatus: "Mountain Shield",
      block: "Resilient",
      culture: "Militaristic / Ancestor respect",
      hdi: "0.87",
      statNotes: [
        "Leader Traits: Generous +2 HDI",
        "Localisation: Nosecrest",
        "Influence: 5.0",
        "Note: 6.166666667"
      ],
    },
  {
      spin: "S2 #21",
      name: "Silker",
      slug: "silker",
      people: "25 000 000",
      government: "Military Dictatorship",
      gdp: "$700B",
      economy: "Eco Toilets / Mercenaries",
      military: "Basic Army 5/10",
      area: "900 000 km2",
      geoPoliticalStatus: "Population Drain",
      block: "Demonbound",
      culture: "Melting pot / Substance Free",
      hdi: "0.31",
      statNotes: [
        "Leader Traits: Architect +2 GDP",
        "Localisation: Feastwater",
        "Influence: 4.0",
        "Note: 5"
      ],
    }
];

